In [1]:
# Read in the anndata object
import anndata as ad
import pandas as pd
import warnings
import re

warnings.filterwarnings('ignore')

In [2]:
# =============================================================================
# Load the full splicing data
# =============================================================================

# Base directories
BASE_DIR = "/gpfs/commons/groups/knowles_lab/Karin/Leaflet-analysis-WD/MOUSE_SPLICING_FOUNDATION"
original_splice_adata = f"{BASE_DIR}/MODEL_INPUT/102025/model_ready_aligned_splicing_data_20251009_024406.h5ad"
full_splice_adata = ad.read_h5ad(original_splice_adata)

In [3]:
print(f"The number of cells in the full splicing data is {full_splice_adata.n_obs}")

The number of cells in the full splicing data is 142315

### We are going to use the original provided cell types (saved in cell_ontology_class) and tissue labels and then manusally sort them into broad cell type, medium cell type and tissue_celltype labels that we will use for all the figures in the manuscript

In [4]:
cell_types_summary = full_splice_adata.obs[["cell_ontology_class", "tissue"]].value_counts()
cell_types_summary = pd.DataFrame(cell_types_summary)
cell_types_summary.to_csv("cell_types_summary_original_labels.csv")

#### This is now the file we are reading that contains the manually curated labels which we will use for everything downstream

In [5]:
full_splice_adata.obs.drop(columns=["medium_cell_type", "broad_cell_type", "specific_cell_type"], inplace=True)

In [7]:
# 1. Read the file
cell_type_mapping = pd.read_csv("/gpfs/commons/home/kisaev/Leaflet-analysis/LeafletFA_Submission2025/Mouse_Splicing_Foundation/Figures/cell_ontology_tissue_OG_Claude_tissue_cell_type_cleaned_nov29.tsv", sep="\t")

In [8]:
cell_type_mapping[cell_type_mapping["tissue_celltype"] == "Lung_Immune"]

    cell_ontology_class broad_cell_type tissue tissue_celltype dataset  count
421           leukocyte          Immune   Lung     Lung_Immune     TMS     34
546          lymphocyte          Immune   Lung     Lung_Immune     TMS      8

In [10]:
mapper_df = cell_type_mapping[["cell_ontology_class", "tissue", "broad_cell_type", "tissue_celltype"]].drop_duplicates()
mapper_df

              cell_ontology_class  tissue    broad_cell_type   tissue_celltype
0                 microglial cell   Brain          Microglia   Brain_Microglia
1                 168_L2/3 IT CTX   Brain  Neuron_Excitatory      Brain_Ex-Ctx
2    fibroblast of cardiac tissue   Heart            Stromal  Heart_Fibroblast
3         hematopoietic stem cell  Marrow    Stem/Progenitor        Marrow_HSC
4                     granulocyte  Marrow             Immune    Marrow_Myeloid
..                            ...     ...                ...               ...
580                 127_L2 IT APr   Brain  Neuron_Excitatory      Brain_Ex-Ctx
581                  382_SMC-Peri   Brain            Stromal    Brain_Pericyte
582                     378_Astro   Brain               Glia   Brain_Astrocyte
583                     369_Oligo   Brain               Glia       Brain_Oligo
584                150_L2 IT ENTm   Brain  Neuron_Excitatory      Brain_Ex-Ctx

[585 rows x 4 columns]

In [11]:
# Need to rename brain tissue to just be "Brain"
# find all cells in splice_adata.obs that contain "Brain" in the tissue column 
brain_cells = full_splice_adata.obs[full_splice_adata.obs["tissue"].str.contains("Brain")].index
# need to first convert to string
full_splice_adata.obs["tissue"] = full_splice_adata.obs["tissue"].astype(str)
# rename these tissues to just be "Brain"
full_splice_adata.obs.loc[brain_cells, "tissue"] = "Brain"

In [12]:
# now need to merge mapper_df onto full_splice_adata.obs on cell_ontology_class and tissue 
# split into brain and non-brain because if brain, we will merge only on cell_ontology_class, but if non-brain, we will merge on cell_ontology_class and tissue 
full_splice_adata.obs = full_splice_adata.obs.merge(mapper_df, on=["cell_ontology_class", "tissue"], how="left")

In [13]:
full_splice_adata.obs[full_splice_adata.obs["tissue_celltype"] == "Lung_Immune"]

,cell_id_index,age,cell_ontology_class,mouse.id,sex,subtissue,tissue,dataset,cell_name,cell_id,cell_clean,seqtech,library_size,total_junction_reads,annotated_junction_reads,unannotated_junction_reads,n_detected_annotated_junctions,n_detected_unannotated_junctions,broad_cell_type,tissue_celltype
9170,9170,3m,leukocyte,3_39_F,F,EPCAM,Lung,TMS,B22_MAA001847,B22_MAA001847,B22_MAA001847,single_cell,21331,19038,18721,317,3228,67,Immune,Lung_Immune
9897,9897,3m,lymphocyte,3_38_F,F,EPCAM,Lung,TMS,B4_MAA001889,B4_MAA001889,B4_MAA001889,single_cell,240994,220929,216818,4111,1286,63,Immune,Lung_Immune
14038,14038,24m,lymphocyte,24_61_M,M,EPCAM,Lung,TMS,C20_B000342,C20_B000342,C20_B000342,single_cell,41035,37945,37668,277,661,13,Immune,Lung_Immune
18959,18959,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,D18_B002946,D18_B002946,D18_B002946,single_cell,29299,26540,25957,583,1094,36,Immune,Lung_Immune
19219,19219,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,D19_B002946,D19_B002946,D19_B002946,single_cell,7159,6721,6700,21,365,10,Immune,Lung_Immune
19666,19666,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,D20_B002946,D20_B002946,D20_B002946,single_cell,27048,25212,24637,575,762,28,Immune,Lung_Immune
27989,27989,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F11_B000342,F11_B000342,F11_B000342,single_cell,7827,6929,6848,81,592,11,Immune,Lung_Immune
28267,28267,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F12_B000342,F12_B000342,F12_B000342,single_cell,11116,10083,9961,122,757,10,Immune,Lung_Immune
28555,28555,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F13_B000342,F13_B000342,F13_B000342,single_cell,110066,100108,98508,1600,1830,48,Immune,Lung_Immune
28834,28834,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F14_B000342,F14_B000342,F14_B000342,single_cell,106406,97685,94376,3309,1846,60,Immune,Lung_Immune
29091,29091,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F15_B000342,F15_B000342,F15_B000342,single_cell,61241,55717,54517,1200,1795,38,Immune,Lung_Immune
29379,29379,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F16_B000342,F16_B000342,F16_B000342,single_cell,118143,105226,102325,2901,2266,61,Immune,Lung_Immune
29655,29655,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F17_B000342,F17_B000342,F17_B000342,single_cell,103717,91799,90175,1624,2196,50,Immune,Lung_Immune
29903,29903,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F18_B000342,F18_B000342,F18_B000342,single_cell,38031,34196,33471,725,1774,47,Immune,Lung_Immune
30159,30159,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F19_B000342,F19_B000342,F19_B000342,single_cell,139987,125246,122422,2824,2350,75,Immune,Lung_Immune
30396,30396,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F1_B000342,F1_B000342,F1_B000342,single_cell,16638,15359,14938,421,466,34,Immune,Lung_Immune
30640,30640,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F20_B000342,F20_B000342,F20_B000342,single_cell,141245,127263,125350,1913,2319,66,Immune,Lung_Immune
30904,30904,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F21_B000342,F21_B000342,F21_B000342,single_cell,162065,145609,143508,2101,1892,74,Immune,Lung_Immune
31144,31144,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F22_B000342,F22_B000342,F22_B000342,single_cell,163801,146817,144256,2561,2471,86,Immune,Lung_Immune
31385,31385,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F2_B000342,F2_B000342,F2_B000342,single_cell,30607,27752,26892,860,541,13,Immune,Lung_Immune
32631,32631,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,F7_B000342,F7_B000342,F7_B000342,single_cell,22173,20382,20015,367,668,23,Immune,Lung_Immune
34490,34490,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,G14_B000342,G14_B000342,G14_B000342,single_cell,50350,46477,45492,985,1039,43,Immune,Lung_Immune
35582,35582,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,G18_B000342,G18_B000342,G18_B000342,single_cell,109904,100082,96913,3169,1835,71,Immune,Lung_Immune
35702,35702,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,G18_B002946,G18_B002946,G18_B002946,single_cell,10049,9286,9076,210,908,35,Immune,Lung_Immune
35828,35828,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,G19_B000342,G19_B000342,G19_B000342,single_cell,5358,4971,4503,468,338,18,Immune,Lung_Immune
35947,35947,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,G19_B002946,G19_B002946,G19_B002946,single_cell,23788,21325,20999,326,896,28,Immune,Lung_Immune
38620,38620,24m,leukocyte,24_61_M,M,EPCAM,Lung,TMS,G8_B000342,G8_B000342,G8_B000342,single_cell,80791,66846,64976,1870,726,31,Immune,Lung_Immune
41408,41408,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,H18_B002946,H18_B002946,H18_B002946,single_cell,30472,27728,26624,1104,1311,58,Immune,Lung_Immune
42641,42641,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,H22_B002946,H22_B002946,H22_B002946,single_cell,27252,24596,23924,672,956,51,Immune,Lung_Immune
43764,43764,18m,lymphocyte,18_46_F,F,EPCAM,Lung,TMS,H6_B000268,H6_B000268,H6_B000268,single_cell,100293,92089,88387,3702,2661,89,Immune,Lung_Immune
47386,47386,3m,lymphocyte,3_39_F,F,EPCAM,Lung,TMS,I19_MAA001847,I19_MAA001847,I19_MAA001847,single_cell,29761,27273,26380,893,2499,78,Immune,Lung_Immune
48143,48143,18m,lymphocyte,18_47_F,F,ENDOMUCIN,Lung,TMS,I22_B000265,I22_B000265,I22_B000265,single_cell,99236,90167,84850,5317,1678,70,Immune,Lung_Immune
49219,49219,18m,lymphocyte,18_47_F,F,EPCAM,Lung,TMS,I5_B002843,I5_B002843,I5_B002843,single_cell,235162,210968,203141,7827,1914,94,Immune,Lung_Immune
53690,53690,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,J21_B002946,J21_B002946,J21_B002946,single_cell,18135,16520,16142,378,1140,42,Immune,Lung_Immune
60552,60552,18m,lymphocyte,18_47_F,F,EPCAM,Lung,TMS,K5_B002843,K5_B002843,K5_B002843,single_cell,152215,138153,135003,3150,1557,75,Immune,Lung_Immune
65300,65300,18m,leukocyte,18_45_M,M,ENDOMUCIN,Lung,TMS,L22_B002258,L22_B002258,L22_B002258,single_cell,211480,193694,187160,6534,1843,97,Immune,Lung_Immune
81972,81972,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,M18_B002946,M18_B002946,M18_B002946,single_cell,57918,53439,52194,1245,1636,62,Immune,Lung_Immune
83008,83008,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,M21_B002946,M21_B002946,M21_B002946,single_cell,25609,23510,22869,641,1250,47,Immune,Lung_Immune
83244,83244,24m,leukocyte,24_58_M,M,EPCAM,Lung,TMS,M22_B002946,M22_B002946,M22_B002946,single_cell,30699,27146,26521,625,966,37,Immune,Lung_Immune
86723,86723,18m,leukocyte,18_47_F,F,EPCAM,Lung,TMS,N15_B002843,N15_B002843,N15_B002843,single_cell,1529,1418,1378,40,209,4,Immune,Lung_Immune
88478,88478,24m,lymphocyte,24_61_M,M,EPCAM,Lung,TMS,N22_B000342,N22_B000342,N22_B000342,single_cell,32534,29184,28618,566,652,23,Immune,Lung_Immune
93164,93164,3m,leukocyte,3_38_F,F,EPCAM,Lung,TMS,O1_MAA001889,O1_MAA001889,O1_MAA001889,single_cell,150716,129353,126766,2587,1784,70,Immune,Lung_Immune

In [14]:
full_splice_adata.obs[full_splice_adata.obs["tissue"] == "Brain"]

,cell_id_index,age,cell_ontology_class,mouse.id,sex,subtissue,tissue,dataset,cell_name,cell_id,cell_clean,seqtech,library_size,total_junction_reads,annotated_junction_reads,unannotated_junction_reads,n_detected_annotated_junctions,n_detected_unannotated_junctions,broad_cell_type,tissue_celltype
6,6,18m,endothelial cell,18_53_M,M,Cortex,Brain,TMS,A10_B000176,A10_B000176,A10_B000176,single_cell,128355,115089,113768,1321,782,25,Endothelial,Brain_Endothelial
43,43,3m,microglial cell,3_38_F,F,Striatum,Brain,TMS,A10_B000825,A10_B000825,A10_B000825,single_cell,42923,37640,36995,645,477,26,Microglia,Brain_Microglia
47,47,24m,microglial cell,24_60_M,M,Striatum,Brain,TMS,A10_B000840,A10_B000840,A10_B000840,single_cell,63555,57927,56177,1750,732,25,Microglia,Brain_Microglia
48,48,24m,microglial cell,24_60_M,M,Hippocampus,Brain,TMS,A10_B000843,A10_B000843,A10_B000843,single_cell,58419,53702,52909,793,513,18,Microglia,Brain_Microglia
54,54,18m,microglial cell,18_47_F,F,Cerebellum,Brain,TMS,A10_B001060,A10_B001060,A10_B001060,single_cell,39178,36024,35389,635,1061,47,Microglia,Brain_Microglia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142310,142310,2m,197_L5 IT CTX,184750,F,VISp,Brain,AB,US-1250275_E2_S86,US-1250275_E2_S86,SRR16457632,single_nuclei,53587,48275,45749,2526,9393,240,Neuron_Excitatory,Brain_Ex-Ctx
142311,142311,2m,204_L5/6 IT CTX,184756,M,VISp,Brain,AB,US-1250275_E2_S87,US-1250275_E2_S87,SRR16457633,single_nuclei,44150,39687,36238,3449,8268,218,Neuron_Excitatory,Brain_Ex-Ctx
142312,142312,2m,257_L5 PT CTX,185199,M,VISp,Brain,AB,US-1250275_E2_S88,US-1250275_E2_S88,SRR16457635,single_nuclei,48161,42726,39975,2751,10177,232,Neuron_Excitatory,Brain_Ex-Ctx
142313,142313,2m,204_L5/6 IT CTX,185200,F,VISp,Brain,AB,US-1250275_E2_S89,US-1250275_E2_S89,SRR16457636,single_nuclei,73787,66108,62267,3841,11739,365,Neuron_Excitatory,Brain_Ex-Ctx
142314,142314,2m,245_L5 PT CTX,184752,F,VISp,Brain,AB,US-1250275_E2_S90,US-1250275_E2_S90,SRR16457637,single_nuclei,24434,21747,20246,1501,7698,198,Neuron_Excitatory,Brain_Ex-Ctx

In [16]:
# use this to make supp table 1 
file_name = "LeafletFA_Supplemental_Table_1.xlsx"
full_splice_adata.obs[["cell_id", "cell_name", "cell_ontology_class", "broad_cell_type", "tissue", "tissue_celltype", "dataset"]].drop_duplicates().to_excel(file_name, index=False)

In [17]:
!pwd

/gpfs/commons/home/kisaev/Leaflet-analysis/LeafletFA_Submission2025/Mouse_Splicing_Foundation/Figures