In [1]:
# Load LeafletSC 
import LeafletSC
import os
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

from LeafletSC.clustering.find_intron_clusters import main as find_intron_clusters
from LeafletSC.clustering.prepare_model_input import main as prep_model_input
from LeafletSC.clustering.find_intron_clusters import visualize_local_events

# define path for saving the output data 
output_path = "/gpfs/commons/projects/knowles_singlecell_splicing/allen-brain/human/lein/"

# we provide a gtf file for the human genome as well to make better sense of the junctions that are detected in cells
# please replace with the path to the gtf file on your system
gtf_file="/gpfs/commons/datasets/controlled/BRAIN_NeMO/human-reference/gencode/gencode.v45.primary_assembly.annotation.gtf" 

# published metadata
metacells = "/gpfs/commons/datasets/controlled/BRAIN_NeMO/human-cortical-taxonomy/General/metadata.csv"

In [2]:
intron_clusters = "/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/LeafletAnalysis/human_cortex_lein_leaflet_50_500000_10_20240514_single_cell.gz" # path to the intron clusters file
output_file = output_path + "lein_human_cortex_leaflet" # name of the output file
print(output_file)
has_genes = "yes" # since we used a gtf file to obtain the intron clusters, we can set this to yes
chunk_size = 5000 # number of junctions to process at a time from the intron clusters files
metadata = None # can replace with path, if metadata is available for cells (cell type, origin, library ID...)

/gpfs/commons/projects/knowles_singlecell_splicing/allen-brain/human/lein/lein_human_cortex_leaflet

In [3]:
prep_model_input(intron_clusters, output_file, has_genes, chunk_size, metadata)

The intron clusters file you provided is /gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/LeafletAnalysis/human_cortex_lein_leaflet_50_500000_10_20240514_single_cell.gz, reading in chunks of 5000 lines
Processing intron clusters

0it [00:00, ?it/s]

539it [00:26, 20.52it/s]

Done processing intron clusters
The number of intron clusters evaluated is 4585
The number of junctions evaluated is 12672
The number of cells evaluated is 2721
The number of clusters with only one junction is 0
A gtf file was used to generate intron clusters
The number of total cells evaluated is 2721
The number of cells per cell type is:
cell_type
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F1S4_160106_001_D01_junctions_with_barcodes.bed    1
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F1S4_160106_003_D01_junctions_with_barcodes.bed    1
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F1S4_160106_006_D01_junctions_with_barcodes.bed    1
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F1S4_160106_007_A01_junctions_with_barcodes.bed    1
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F1S4_160106_007_C01_junctions_with_barcodes.bed    1
                                                                                                                         ..
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F2S4_190227_092_F01_junctions_with_barcodes.bed    1
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F2S4_190227_092_G01_junctions_with_barcodes.bed    1
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F2S4_190227_095_B01_junctions_with_barcodes.bed    1
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F2S4_190227_098_D01_junctions_with_barcodes.bed    1
/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F2S4_190227_100_F01_junctions_with_barcodes.bed    1
Name: cell_type, Length: 2721, dtype: int64
['F1S4_160106_001_D01_/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F1S4_160106_001_D01_junctions_with_barcodes.bed'
 'F1S4_160106_003_D01_/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F1S4_160106_003_D01_junctions_with_barcodes.bed'
 'F1S4_160106_006_D01_/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F1S4_160106_006_D01_junctions_with_barcodes.bed'
 ...
 'F2S4_190227_095_B01_/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F2S4_190227_095_B01_junctions_with_barcodes.bed'
 'F2S4_190227_098_D01_/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F2S4_190227_098_D01_junctions_with_barcodes.bed'
 'F2S4_190227_100_F01_/gpfs/commons/datasets/controlled/BRAIN_NeMO/lein-human-cortex/Leaflet/F2S4_190227_100_F01_junctions_with_barcodes.bed']
You can find the resulting file at /gpfs/commons/projects/knowles_singlecell_splicing/allen-brain/human/lein/lein_human_cortex_leaflet.h5
Done generating input file for Leaflet model. This process took 54 seconds

In [4]:
# read in the metadata file
metacells = pd.read_csv(metacells)
metacells.head()

,sample_name,exp_component_name,specimen_type,cluster_color,cluster_order,cluster_label,class_color,class_order,class_label,subclass_color,...,cell_type_alt_alias_order,cell_type_alt_alias_label,cell_type_designation_color,cell_type_designation_order,cell_type_designation_label,external_donor_name_color,external_donor_name_order,external_donor_name_label,outlier_call,outlier_type
0,F2S4_160113_027_A01,LS-15005h_S01_E1-50,nucleus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,#3DCC3D,2,H200.1025,True,Outlier L1-3 SST OR2AD1P
1,F2S4_160113_027_B01,LS-15005h_S02_E1-50,nucleus,#E170FE,32.0,Inh L2-5 VIP TOX2,#0066FF,4.0,GABAergic,#996517,...,32.0,NaN,#E170FE,32.0,Neuron 032,#3DCC3D,2,H200.1025,False,NaN
2,F2S4_160113_027_C01,LS-15005h_S03_E1-50,nucleus,#8E5864,2.0,Inh L1 LAMP5 GGT8P,#0066FF,4.0,GABAergic,#FF7373,...,2.0,NaN,#8E5864,2.0,Neuron 002,#3DCC3D,2,H200.1025,False,NaN
3,F2S4_160113_027_D01,LS-15005h_S04_E1-50,nucleus,#8B5862,1.0,Inh L1 LAMP5 NDNF,#0066FF,4.0,GABAergic,#FF7373,...,1.0,NaN,#8B5862,1.0,Neuron 001,#3DCC3D,2,H200.1025,False,NaN
4,F2S4_160113_027_E01,LS-15005h_S05_E1-50,nucleus,#CF6EC9,34.0,Inh L1-3 VIP ZNF322P1,#0066FF,4.0,GABAergic,#996517,...,34.0,NaN,#CF6EC9,34.0,Neuron 034,#3DCC3D,2,H200.1025,False,NaN

In [5]:
metacells[metacells["sample_name"] == "F1S4_160106_001_B01"]

,sample_name,exp_component_name,specimen_type,cluster_color,cluster_order,cluster_label,class_color,class_order,class_label,subclass_color,...,cell_type_alt_alias_order,cell_type_alt_alias_label,cell_type_designation_color,cell_type_designation_order,cell_type_designation_label,external_donor_name_color,external_donor_name_order,external_donor_name_label,outlier_call,outlier_type
162,F1S4_160106_001_B01,LS-15051_S02_E1-50,nucleus,#996A0E,41.0,Inh L4-6 SST MTHFD2P6,#0066FF,4.0,GABAergic,#FFE500,...,41.0,NaN,#996A0E,41.0,Neuron 041,#171799,3,H200.1030,False,NaN