In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# set working dir to /gpfs/commons/datasets/controlled/BRAIN_NeMO/human-cortical-taxonomy/General 
os.chdir('/gpfs/commons/datasets/controlled/BRAIN_NeMO/human-cortical-taxonomy/General')

# Metadata file metadata.csv read in as pd df
metadata = pd.read_csv('metadata.csv')
metadata.head()

,sample_name,exp_component_name,specimen_type,cluster_color,cluster_order,cluster_label,class_color,class_order,class_label,subclass_color,...,cell_type_alt_alias_order,cell_type_alt_alias_label,cell_type_designation_color,cell_type_designation_order,cell_type_designation_label,external_donor_name_color,external_donor_name_order,external_donor_name_label,outlier_call,outlier_type
0,F2S4_160113_027_A01,LS-15005h_S01_E1-50,nucleus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,#3DCC3D,2,H200.1025,True,Outlier L1-3 SST OR2AD1P
1,F2S4_160113_027_B01,LS-15005h_S02_E1-50,nucleus,#E170FE,32.0,Inh L2-5 VIP TOX2,#0066FF,4.0,GABAergic,#996517,...,32.0,NaN,#E170FE,32.0,Neuron 032,#3DCC3D,2,H200.1025,False,NaN
2,F2S4_160113_027_C01,LS-15005h_S03_E1-50,nucleus,#8E5864,2.0,Inh L1 LAMP5 GGT8P,#0066FF,4.0,GABAergic,#FF7373,...,2.0,NaN,#8E5864,2.0,Neuron 002,#3DCC3D,2,H200.1025,False,NaN
3,F2S4_160113_027_D01,LS-15005h_S04_E1-50,nucleus,#8B5862,1.0,Inh L1 LAMP5 NDNF,#0066FF,4.0,GABAergic,#FF7373,...,1.0,NaN,#8B5862,1.0,Neuron 001,#3DCC3D,2,H200.1025,False,NaN
4,F2S4_160113_027_E01,LS-15005h_S05_E1-50,nucleus,#CF6EC9,34.0,Inh L1-3 VIP ZNF322P1,#0066FF,4.0,GABAergic,#996517,...,34.0,NaN,#CF6EC9,34.0,Neuron 034,#3DCC3D,2,H200.1025,False,NaN

In [3]:
# try reading mtg facs metadata file 
mtg="/gpfs/commons/datasets/controlled/BRAIN_NeMO/human-cortex-mtg/mtg_facs_metadata.csv"
mtg_metadata = pd.read_csv(mtg)
mtg_metadata.head()

,sample_name,exp_component_name,cl.sep,PE-A Mean,FSC-A Mean,SSC-A Mean,DAPI-A Mean,cluster,cluster_type
0,F1S4_170118_004_E01,SM-D9D7S_S29_E1-50,0.650100,3055.0,44810.0,9073.0,9056.0,Inh L1-4 LAMP5 LCP2,inh
1,F1S4_170125_069_F01,SM-D9D7F_S22_E1-50,0.630866,1770.0,58551.0,14292.0,8401.0,Inh L1-4 LAMP5 LCP2,inh
2,F1S4_170207_048_A01,SM-D9D7J_S73_E1-50,0.642934,972.0,54664.0,11064.0,8047.0,Inh L1-4 LAMP5 LCP2,inh
3,F1S4_170215_071_D01,SM-D9D6S_S92_E1-50,0.628486,1877.0,29711.0,8087.0,8940.0,Inh L1-4 LAMP5 LCP2,inh
4,F1S4_170321_054_D01,SM-D9D8Y_S44_E1-50,0.628262,NaN,NaN,NaN,NaN,Inh L1-4 LAMP5 LCP2,inh

In [4]:
mtg_metadata[mtg_metadata["sample_name"] == "F2S4_170405_016_D01"]

# should be coming from specimen H16.03.004

Empty DataFrame
Columns: [sample_name, exp_component_name, cl.sep, PE-A Mean, FSC-A Mean, SSC-A Mean, DAPI-A Mean, cluster, cluster_type]
Index: []

In [ ]:
metadata.shape

In [ ]:
metadata.outlier_call.value_counts()

In [ ]:
# remove outliter_call True 
metadata = metadata[metadata.outlier_call == False]
metadata.iloc[0]

In [ ]:
metadata.cluster_label.value_counts()

In [ ]:
metadata.class_label.value_counts()

In [ ]:
metadata.subclass_label.value_counts()

In [ ]:
metadata.region_label.value_counts()